frontend/controllers/MessageController.php
<?php

class MessageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','create'),
				'users'=>array('@'),
			),
		);
	}


	public function actionCreate($user_id)
	{
		// прописал все заново, и заработало
		$userId = Profile::model()->find('user_id = :user_id', array(':user_id' => $user_id));

		$model=new Message;

		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];
			$model->id_to = $userId->user_id;
			if($model->save())
				$this->redirect(array('outbox'));

		}

		$this->render('create',array(
			'model'=>$model,
			'userId'=>$userId,
		));
	}


	public function loadModel($user_id)
	{
		$model=Profile::model()->findByPk($user_id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{

		// $model = new Profile;

		$criteria = new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_to = $curentUser" ||  "id_from = $curentUser";

        $dataProvider = new CActiveDataProvider('Message', array(
        		'criteria' => $criteria,
        	));

        $this->render ('index', array(
        	'dataProvider'=>$dataProvider,
        	// 'model' => $model,
        	));


		// $userId = Profile::model()->find('user_id = :user_id', array(':user_id' => $user_id));

		// $model = new Profile;

		// $criteria=new CDbCriteria;
		// $curentUser = Yii::app()->user->id;
		// $criteria -> condition = "id_from = $curentUser";
		

		// $dataProvider=new CActiveDataProvider('Message', array(
		// 	'criteria' => $criteria,));
		// $this->render('index',array(
		// 	'dataProvider'=>$dataProvider,
		// 	'model' => $model,
		// 	// 'userId' => $userId,
		// ));
	}
	// Входящие сообщения
	public function actionInbox(){


		$criteria=new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_to = $curentUser";
		

		$dataProvider=new CActiveDataProvider('Message', array(
			'criteria' => $criteria,));
		$this->render('inbox',array(
			'dataProvider'=>$dataProvider,
		));
	}
	// Исходящие сообщения
	public function actionOutbox(){
		$criteria=new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_from = $curentUser";
		

		$dataProvider=new CActiveDataProvider('Message', array(
			'criteria' => $criteria,));
		$this->render('outbox',array(
			'dataProvider'=>$dataProvider,
		));

	}


}

frontend/controllers/ProfileController.php
<?php
	/**
	* Контроллер профиля
	*/
	class ProfileController extends Controller
	{
		
		public $layout='//layouts/column1';
		private $_model;


		public function actionEditprofile()

		{
			$model = $this -> loadmodel();

			if (isset($_POST['Profile'])) {
	            $model->attributes = $_POST['Profile'];

	            $file_image =  CUploadedFile::getInstance($model, 'image');

	            

        		if(is_object($file_image) && get_class($file_image) === 'CUploadedFile')
            		$model->image = $file_image;


	            	if ($model->save())
	            		{
	            			// Удаление не работает.
	            			if(file_exists($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'/images/'. '/avatar_images'.'/'.$model->image))
									{
										//удаляем картинку и все её thumbs
										@unlink($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'/images/'. '/avatar_images'.'/'.$model->image);
										@unlink($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'./images'. '/avatar_images'.'/thumbs/'.$model->image);
										@unlink($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'./images'. '/avatar_images'.'/thumbs_small/'.$model->image);						
										$model->image = '';
									}

				            if(is_object($file_image)) 
					            {
					            	// сохранение файла на сервер под именем id+image_name
					            	
					            	$dir=$_SERVER['DOCUMENT_ROOT'].Yii::app()->request->baseUrl.'/images/' . '/avatar_images';
					            	$file=$dir.'/'.$model->user_id.'_'.$model->image;
					            	$model->image->saveAs($file);
					            	//Используем функции расширения CImageHandler;
									$ih = new CImageHandler(); //Инициализация
									Yii::app()->ih 
									->load($file) //Загрузка оригинала картинки
									->thumb('200', false) //Создание превьюшки шириной 200px
									->save($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'/images/'. '/avatar_images'.'/thumbs/'.$model->user_id.'_'.$model->image) //Сохранение превьюшки в папку thumbs
									->reload() //Снова загрузка оригинала картинки
									->thumb('50', '50') //Создание превьюшки размером 50px
									->save($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'/images/'. '/avatar_images'.'/thumbs_small/'.$model->user_id.'_'.$model->image) //Сохранение превьюшки в папку thumbs_small
									->reload()//Снова загрузка оригинала картинки
									->thumb('800', '800') //Создание превьюшки размером 800px
									->save($_SERVER['DOCUMENT_ROOT'].Yii::app()->urlManager->baseUrl.'/images/'. '/avatar_images'.'/'.$model->user_id.'_'.$model->image) //Сохранение большой картинки в папку
									;
					            }
					        
				            $this->redirect(array('profile', 'id' => $model->user_id));
				        }

	        	        
		    }

			$this->render('editprofile', array(
				'model' => $this -> loadmodel()
			));

		}


		public function actionProfile()

		{
			$this->render('profile', array(
				'model' => $this -> loadmodel()
			));

		}

		public function actionSeeProfile($user_id)
		
		{
			$userProfile = Profile::model()->find('user_id = :user_id', array(':user_id' => $user_id));

			$model=new Message;

			$dataProvider = new CActiveDataProvider('Profile');

			$this->render('seeprofile',array(
				'model'=>$model,
				'userProfile'=>$userProfile,
				'dataProvider' => $dataProvider,
			));
		}

		public function loadModel()
		{
			if($this->_model===null)
			{
				if(isset($_GET['id']))
					$this->_model=Profile::model()->findbyPk($_GET['id']);
				if($this->_model===null)
					throw new CHttpException(404,'The requested page does not exist.');
			}
			return $this->_model;
		}
	}
?>

frontend/controllers/SiteController.php
<?php
/**
 * SiteController.php
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/23/12
 * Time: 12:25 AM
 */
class SiteController extends Controller {

	public function accessRules() {
		return array(
			// not logged in users should be able to login and view captcha images as well as errors
			array('allow', 'actions' => array('index', 'captcha', 'login', 'error', 'KK')),
			// logged in users can do whatever they want to
			array('allow', 'users' => array('@')),
			// not logged in users can't do anything except above
			array('deny'),
		);
	}

	/**
	 * Declares class-based actions.
	 * @return array
	 */
	public function actions() {
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
		);
	}

	/* open on startup */
	public function actionIndex() {
        // если пользователь гость - выводится форма входа
        if (Yii::app()->user->isGuest){
    		$model = new LoginForm;

            // if it is ajax validation request
            if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset($_POST['LoginForm'])) {
                $model->attributes = $_POST['LoginForm'];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(array('profile/profile', 'id'=>Yii::app()->user->id));
            }
            // display the login form
            $this->render('index', array('model' => $model));
        }
        // если не гость - выводится профиль
        else{
            $model = new Profile;
            $this->render('/profile/profile', array('model' => $model));
        }
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError() {
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the login page
	 */
    public function actionLogin() {

        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(array('profile/profile', 'id'=>Yii::app()->user->id));
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

	
	public function validatePassword($password)
    {
        return crypt($password,$this->password)===$this->password;
    }
 
    public function hashPassword($password)
    {
        return crypt($password, $this->generateSalt());
    }

    public function actionPeople(){

        $dataProvider = new CActiveDataProvider('Profile');

        $this->render ('people', array('dataProvider'=>$dataProvider));


    }


}

frontend/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

frontend/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div class="span-19">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="span-5 last">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Operations',
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'operations'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

frontend/views/layouts/main.php
<?php
/**
 * main.php
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/23/12
 * Time: 12:31 AM
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/normalize.css">
	
	<!-- Use the .htaccess and remove these lines to avoid edge case issues. More info: h5bp.com/b/378 -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title><?php echo h($this->pageTitle); /* using shortcut for CHtml::encode */ ?></title>
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="viewport" content="width=device-width,initial-scale=1">


	<link rel="stylesheet" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/styles.css"/>
	<!--using less instead? file not included-->
	<!--<link rel="stylesheet/less" type="text/css" href="/less/styles.less">-->

	<!-- create your own: http://modernizr.com/download/-->
	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/modernizr-2.6.2.js"></script>

	<!--<script src="/less/less-1.3.0.min.js"></script>-->
	<link rel="shortcut icon" href="<?php echo Yii::app()->request->baseUrl; ?>/images/favicon.ico">
</head>

<body>
<div class="container" id="page">
	<?php
	 $this->widget('bootstrap.widgets.TbNavbar', array(
	'type' => 'inverse', // null or 'inverse'
	'brand' => 'Friend social',
	'brandUrl' => "Yii::app()->request->baseUrl/site/index",
	'collapse' => true, // requires bootstrap-responsive.css
	'items' => array(
		array(
			'class' => 'bootstrap.widgets.TbMenu',
			'items' => array(
				array('label' => 'Регистрация', 'url' => array('/user/registration'), 'visible'=> Yii::app()->user->isGuest), 
				array(
			            		'label' => 'Профиль', 
			            		'url' => array('/profile/profile', 'id'=>Yii::app()->user->id), 
			            		'visible' => !Yii::app()->user->isGuest
            				),
				array(
			            		'label' => 'Люди', 
			            		'url' => array('/site/people'), 
			            		'visible' => !Yii::app()->user->isGuest
            				),
				array(
			            		'label' => 'Сообщения', 
			            		// 'url' => array('/message/index'), 
			            		'visible' => !Yii::app()->user->isGuest,
			            		'url' => array('message/index'),
			            		// 'items' => array(
			            		// 		array(
						           //  		'label' => 'Входящие', 
						           //  		'url' => array('/message/inbox'), 
						           //  		'visible' => !Yii::app()->user->isGuest
            					// 		),
			            		// 		array(
						           //  		'label' => 'Исходящие', 
						           //  		'url' => array('/message/outbox'), 
						           //  		'visible' => !Yii::app()->user->isGuest
            					// 		),
			            		// 	),
            				),
			
			),
		),
		
		//(!Yii::app()->user->isGuest) ? '<p class="navbar-text pull-right">Вошли как <a href="#">' . Yii::app()->user->name . '</a></p>' : '',
		

		array(
            'class'=>'bootstrap.widgets.TbMenu',
            'htmlOptions'=>array('class'=>'pull-right'),
            'items'=>array(
            	array(
			            		'label' => 'Login', 
			            		'url' => array('/site/login'), 
			            		'visible' => Yii::app()->user->isGuest
			            	),
            	array(
            		'label'=>Yii::app()->user->name,
            		'visible'=>!Yii::app()->user->isGuest,
            		'items'=>array(
            				array(
			            		'label' => 'Профиль', 
			            		'url' => array('/profile/profile', 'id'=>Yii::app()->user->id), 
			            		'visible' => !Yii::app()->user->isGuest
            				),
			            	array(
			            		'label'=>'Редактировать профиль', 
			            		'url'=>array('/profile/editprofile', 'id'=>Yii::app()->user->id), 
			            		'visible' => !Yii::app()->user->isGuest
			            	),
			            	
							array('label' => 'Logout (' . Yii::app()->user->name . ')', 
								'url' => array('/site/logout')
							), 
            		),
            	)
            ),
        ),



	),
)); 
?>
	<!-- mainmenu -->
	<div class="container" style="margin-top:80px">
		<?php if (isset($this->breadcrumbs)): ?>
			<?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(
			'links' => $this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
		<?php endif?>

		<?php echo $content; ?>
		<hr/>
		<div id="footer">
			<!-- Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/> -->
			<!-- All Rights Reserved.<br/> -->
			<?php
			 // echo Yii::powered(); 
			 ?>
		</div>
		<!-- footer -->
	</div>
</div>




<!-- Google Analytics -->
<script>
	var _gaq=[['_setAccount','<?php echo param('google.analytics.account'); // check global.php shortcut file at "common/lib/" ?>'],['_trackPageview']];
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
		g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
		s.parentNode.insertBefore(g,s)}(document,'script'));
</script>
</body>
</html>