backend/controllers/SiteController.php
<?php
/**
 * SiteController.php
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/24/12
 * Time: 1:21 AM
 */

class SiteController extends Controller
{
	/**
	 * @return array list of action filters (See CController::filter)
	 */
	public function filters()
	{
		return array('accessControl');
	}

	/**
	 * @return array rules for the "accessControl" filter.
	 */
	public function accessRules()
	{
		return array(
			array('allow', // Allow registration form for anyone
				'actions' => array('index', 'login', 'logout', 'contact', 'captcha', 'error', 'test'),
			),
			array('allow', // Allow all actions for logged in users ("@")
				'users' => array('@'),
			),
			array('deny'), // Deny anything else
		);
	}

	/**
	 *
	 * @return array actions
	 */
	public function actions()
	{
		return array(
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
				'foreColor' => 0x0099CC,
			),
			'page' => array(
				'class' => 'CViewAction',
			),
		);
	}

	/**
	 * Renders index page
	 */
	public function actionIndex()
	{
		$this->render('index');
	}

	/**
	 * Renders contact page
	 * todo: does nothing but rendering, proper functionality to be created
	 */
	public function actionContact()
	{
		$model = new ContactForm;
		if (isset($_POST['ContactForm']))
		{
			$model->attributes = $_POST['ContactForm'];
			if ($model->validate())
			{
				/** example code */
//				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
//				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
//				$headers="From: $name <{$model->email}>\r\n".
//					"Reply-To: {$model->email}\r\n".
//					"MIME-Version: 1.0\r\n".
//					"Content-type: text/plain; charset=UTF-8";
//
//				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
//				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
//				$this->refresh();
			}
		}
		$this->render('contact', array('model' => $model));

	}

	/**
	 * Action to render the error
	 * todo: design proper error page
	 */
	public function actionError()
	{
		if ($error = app()->errorHandler->error)
		{
			if (app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Action to render login form or handle user's login
	 * and redirection
	 */
	public function actionLogin()
	{
		$model = new LoginForm();

		if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form')
		{
			echo CActiveForm::validate($model, array('username', 'password', 'verifyCode'));
			Yii::app()->end();
		}

		if (isset($_POST['LoginForm']))
		{
			$model->attributes = $_POST['LoginForm'];
			if ($model->validate(array('username', 'password', 'verifyCode')) && $model->login())
				$this->redirect(user()->returnUrl);
		}

		$sent = r()->getParam('sent', 0);
		$this->render('login', array(
			'model' => $model,
			'sent' => $sent,
		));
	}

	/**
	 * This is the action that handles user's logout
	 */
	public function actionLogout()
	{
		user()->logout();
		$this->redirect(app()->homeUrl);
	}

}

frontend/controllers/MessageController.php
<?php

class MessageController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column1';
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','create'),
				'users'=>array('@'),
			),
		);
	}


	public function actionCreate($user_id)
	{
		// прописал все заново, и заработало
		$userId = Profile::model()->find('user_id = :user_id', array(':user_id' => $user_id));

		$model=new Message;

		if(isset($_POST['Message']))
		{
			$model->attributes=$_POST['Message'];
			$model->id_to = $userId->user_id;
			if($model->save())
				$this->redirect(array('outbox'));

		}

		$this->render('create',array(
			'model'=>$model,
			'userId'=>$userId,
		));
	}


	public function loadModel($user_id)
	{
		$model=Profile::model()->findByPk($user_id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{

		// $model = new Profile;

		$criteria = new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_to = $curentUser" ||  "id_from = $curentUser";

        $dataProvider = new CActiveDataProvider('Message', array(
        		'criteria' => $criteria,
        	));

        $this->render ('index', array(
        	'dataProvider'=>$dataProvider,
        	// 'model' => $model,
        	));


		// $userId = Profile::model()->find('user_id = :user_id', array(':user_id' => $user_id));

		// $model = new Profile;

		// $criteria=new CDbCriteria;
		// $curentUser = Yii::app()->user->id;
		// $criteria -> condition = "id_from = $curentUser";
		

		// $dataProvider=new CActiveDataProvider('Message', array(
		// 	'criteria' => $criteria,));
		// $this->render('index',array(
		// 	'dataProvider'=>$dataProvider,
		// 	'model' => $model,
		// 	// 'userId' => $userId,
		// ));
	}
	// Входящие сообщения
	public function actionInbox(){


		$criteria=new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_to = $curentUser";
		

		$dataProvider=new CActiveDataProvider('Message', array(
			'criteria' => $criteria,));
		$this->render('inbox',array(
			'dataProvider'=>$dataProvider,
		));
	}
	// Исходящие сообщения
	public function actionOutbox(){
		$criteria=new CDbCriteria;
		$curentUser = Yii::app()->user->id;
		$criteria -> condition = "id_from = $curentUser";
		

		$dataProvider=new CActiveDataProvider('Message', array(
			'criteria' => $criteria,));
		$this->render('outbox',array(
			'dataProvider'=>$dataProvider,
		));

	}


}

frontend/controllers/SiteController.php
<?php
/**
 * SiteController.php
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/23/12
 * Time: 12:25 AM
 */
class SiteController extends Controller {

	public function accessRules() {
		return array(
			// not logged in users should be able to login and view captcha images as well as errors
			array('allow', 'actions' => array('index', 'captcha', 'login', 'error', 'KK')),
			// logged in users can do whatever they want to
			array('allow', 'users' => array('@')),
			// not logged in users can't do anything except above
			array('deny'),
		);
	}

	/**
	 * Declares class-based actions.
	 * @return array
	 */
	public function actions() {
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha' => array(
				'class' => 'CCaptchaAction',
				'backColor' => 0xFFFFFF,
			),
		);
	}

	/* open on startup */
	public function actionIndex() {
        // если пользователь гость - выводится форма входа
        if (Yii::app()->user->isGuest){
    		$model = new LoginForm;

            // if it is ajax validation request
            if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
                echo CActiveForm::validate($model);
                Yii::app()->end();
            }

            // collect user input data
            if (isset($_POST['LoginForm'])) {
                $model->attributes = $_POST['LoginForm'];
                // validate user input and redirect to the previous page if valid
                if ($model->validate() && $model->login())
                    $this->redirect(array('profile/profile', 'id'=>Yii::app()->user->id));
            }
            // display the login form
            $this->render('index', array('model' => $model));
        }
        // если не гость - выводится профиль
        else{
            $model = new Profile;
            $this->render('/profile/profile', array('model' => $model));
        }
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError() {
		if ($error = Yii::app()->errorHandler->error) {
			if (Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the login page
	 */
    public function actionLogin() {

        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(array('profile/profile', 'id'=>Yii::app()->user->id));
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout() {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

	
	public function validatePassword($password)
    {
        return crypt($password,$this->password)===$this->password;
    }
 
    public function hashPassword($password)
    {
        return crypt($password, $this->generateSalt());
    }

    public function actionPeople(){

        $dataProvider = new CActiveDataProvider('Profile');

        $this->render ('people', array('dataProvider'=>$dataProvider));


    }


}

frontend/views/site/_view.php
<?php
/* @var $this UserController */
/* @var $data User */
?>

<div class="view">
	<hr />
	<b><?php echo CHtml::encode($data->getAttributeLabel('firstname')); ?>:</b>
	<?php echo CHtml::encode($data->firstname), ' ', CHtml::encode($data->lastname); ?>
	<br /><img src="<?php  echo  Yii::app()->request->baseUrl.'/images/avatar_images/'.$data->image ?>" alt="" width="50"><br />
	<?php echo CHtml::link('Профиль', array('profile/seeprofile', 'user_id'=>$data->user_id)); ?>	<br />
	<?php echo CHtml::link('Добавить в друзья', array('message/create', 'user_id'=>$data->user_id)); ?>	<br />
	<?php echo CHtml::link('Написать сообщение', array('message/create', 'user_id'=>$data->user_id)); ?>	<br />
	

</div>

frontend/views/site/error.php
<?php
/**
 * error.php
 *
 * General view file to display error messages
 * Change to suit your needs.
 *
 * @see errHandler at the main.php configuration file
 *
 * @author: antonio ramirez <antonio@clevertech.biz>
 * Date: 7/22/12
 * Time: 8:27 PM
 */
$this->pageTitle .= ' - Error';
?>

<div class="error_page">
	<div><?php echo CHtml::encode($message) ?></div>

	<small>(Error <?php echo $code ?>)</small>
</div><!-- .error_page -->

frontend/views/site/index.php
<?php
$this->pageTitle=Yii::app()->name . ' - Home';
?>

<div class="form">
	<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'htmlOptions'=>array('class'=>'well'),
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>
	
	<p class="note">Для входа в систему введите логин и пароль.</p>
	<!-- <p class="note">Поля помеченные <span class="required">*</span> обязательны для заполнения</p> -->

	<?php echo $form->textFieldRow($model, 'username', array('class'=>'span3'));?>
	<?php echo $form->passwordFieldRow($model, 'password', array('class'=>'span3'));?>




	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit','type'=>'primary','label'=>'Вход', 'icon'=>'ok'));?>
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset','label'=>'Сбросить', 'icon'=>'remove'));?>
	</div>

	<?php $this->endWidget(); ?>
</div><!-- form -->

frontend/views/site/login.php
<?php
/* @var $this SiteController */
/* @var $model LoginForm */
/* @var $form CActiveForm  */

// $this->pageTitle=Yii::app()->name . ' - Login';
// $this->breadcrumbs=array(
// 	'Login',
// );
?>


<div class="form">
	<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'htmlOptions'=>array('class'=>'well'),
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<!-- <p class="note">Fields with <span class="required">*</span> are required.</p> -->

	<?php echo $form->textFieldRow($model, 'username', array('class'=>'span3'));?>
	<?php echo $form->passwordFieldRow($model, 'password', array('class'=>'span3'));?>




	<div class="form-actions">
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit','type'=>'primary','label'=>'Вход', 'icon'=>'ok'));?>
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'reset','label'=>'Сбросить', 'icon'=>'remove'));?>
	</div>

	<?php $this->endWidget(); ?>
</div><!-- form -->









<!-- <h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'login-form',
	'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<div class="row">
		<?php echo $form->labelEx($model,'username'); ?>
		<?php echo $form->textField($model,'username'); ?>
		<?php echo $form->error($model,'username'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'password'); ?>
		<?php echo $form->passwordField($model,'password'); ?>
		<?php echo $form->error($model,'password'); ?>
		<p class="hint">
			Hint: You may login with <kbd>demo</kbd>/<kbd>demo</kbd> or <kbd>admin</kbd>/<kbd>admin</kbd>.
		</p>
	</div>

	<div class="row rememberMe">
		<?php echo $form->checkBox($model,'rememberMe'); ?>
		<?php echo $form->label($model,'rememberMe'); ?>
		<?php echo $form->error($model,'rememberMe'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Login'); ?>
	</div>

<?php $this->endWidget(); ?>
</div> --><!-- form -->

frontend/views/site/people.php
<?php echo "Страница с пользователями"; ?> 
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>